/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUdGcmJRdHVrZ2lrZG9aeGVEajNDVjMrMitORVFoMlZJSFA2b0lXUEtXbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoianFEL2NuZUhwUG1QZ1MrdXowajZCRjhiTThtVGFpcENhVzIzMmtGazlCcz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrSE1mSWhLdndpbktZMll3U00vWlZhOERMUUV0WGhDa0c1cWQyblV1YjNrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjNjhRZzFPZU1uaUJZcm40TS8yMytpeEs3WDhjMkxCY0dEcWNaelJqTDFnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhMWjVIcGN3RXJFdDlRWFl6YXZCcGR4Uk5rNGJxSFJmKytsZEkwZkI3Mkk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkZnenpvNUZIQ0dJTGZ3b1liaWVRcVlZSHR3MWN2OC9GbHd2cnFFajlhR1E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0hPSE5ZdEtLOGFWc1Z5VDJuRGM5NlJFVDJNTDFKSDVXN041c2JYMTVHYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicHM1Sm5USVZodFEzSEtOdHE5REFUUEJpd2lWMFg3dFJwY3kyVjhwNWRXTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik5wSGNCa2hZUTRqSWRMWjJaeVJIRk1FSHovVjd1MGNVM01yK0NrSm8zVUIxN1FvSWlYZFcvTmxVNDhSb05TVUN5OHQ2V1VEbWJhcEdGSlU3ekVCQUN3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjA3LCJhZHZTZWNyZXRLZXkiOiJaalgvZDh6Lys4S1dXeFgxOXZjQytwZWxRZUJMa3F2YW96RmZBbHFxWmIwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2Mzc3NjM4ODY4OUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIxNDRGQkRBRjQ1REY2QzdCNTZCM0IwMDM0QURFMEFFNCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMwODE4MDkxfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNjM3NzYzODg2ODlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMzE4MTlFRDYwNzA1ODdFQUE2NTE1RTBFOUZCMTk1MTUifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMDgxODA5Mn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiV1Zzd0g5U2VUT3VMU196X3VwVVJvQSIsInBob25lSWQiOiJlYmFiMGRjOS0yN2Y3LTQ5NDktODg3ZS0xNDFhNDQxNTg4NjYiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicVZxWU9ra0xTVzRUdi93b0tjVGg1anVQN0o4PSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjdwNEFST0MzMkNWUllNdFkyQ3ZCaTZ0bkJnST0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJONE5ROFdDTSIsIm1lIjp7ImlkIjoiMjYzNzc2Mzg4Njg5OjVAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0pPZjVQSUZFSnZncUxrR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Iml2b0U1emVpY2dabmhwRm5sUEprSDM4NTFCVzFwY2N3bmllRFJMTWRsaHc9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImZHdzBhdHF5bHdnUzl0UUNuUXV2ZWpNL20wUWhVV3R0VWsram0rRzJyZ1RkcVBkRGFqQXEzb2RWOUI1cjBWMjloWDdvVlpkM1p5ZllwSHdDb3ZmQUFnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJGcWYvSEt5c2llcHBVbk5zb0prTWNhM2dqUTBiYWg3dWo2QUZrL1YyS0RJZGlqazdjTFJiUGxXSW54R2NGZ3ZvaFMvaW9RZmQwV0xnZFNwNCs1MFBBdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI2Mzc3NjM4ODY4OTo1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQllyNkJPYzNvbklHWjRhUlo1VHlaQjkvT2RRVnRhWEhNSjRuZzBTekhaWWMifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzA4MTgwODgsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTTIwIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'AKIO-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
